### PR TITLE
Add support for credit and video data and fix some bugs

### PR DESCRIPTION
**Pull request by openjck**
Supersedes #7

### CODE REVIEW

**Comment by openjck** [comment]
I'll self-merge this after testing on ScraperWiki.

**Comment by openjck** [comment]
Looks good to me. Thanks so much, @dsbeckham. Huge improvement.

**Comment by dsbeckham** [comment]
No problem! It seems that morph.io isn't liking your requirements.txt file, though. I think it can't read from requirements-scraperwiki.txt. I'm not sure why that is (perhaps it's looking for the file locally rather than on the repository?), but you might just have to put that contents of that file back in requirements.txt.

**Comment by openjck** [comment]
Gotcha, that makes sense. I pushed up a new commit and I'll re-try the scraper now.

**Pull request merged**
